language: java
jdk:
  - openjdk21

services:
  - docker

before_script:
  - echo "Starting Travis build for Spring Petclinic..."

script:
  - docker build -t spring-petclinic:build-latest .

after_success:
  - echo "Travis build completed successfully!"
  - curl -X POST https://voluptuously-stomatous-jeanmarie.ngrok-free.dev/webhook
